<?php

namespace AppBundle\Repository;

/**
 * RoomTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomTableRepository extends \Doctrine\ORM\EntityRepository
{
}
