<?php

namespace AppBundle\Repository;

/**
 * TableOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
