<?php

namespace AppBundle\Repository;

/**
 * TableOrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableOrderLineRepository extends \Doctrine\ORM\EntityRepository
{
}
