_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health

front:
    resource: '@AppBundle/Controller/Front'
    type: annotation
    
admin:
    resource: '@AppBundle/Controller/Admin'
    type: annotation
    prefix: /admin
